image: node

before_script:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.87.0/hugo_0.87.0_Linux-64bit.deb
  - dpkg -i hugo*.deb
  - hugo version

test:
  script:
  - hugo
  except:
  - master

pages:
  script:
  - npm install
  - npm run build
  - hugo
  artifacts:
    paths:
    - public
  only:
  - master
