# Site settings
baseURL = "https://www.repairrabbit.co/"
languageCode = "en-us"
title = "RepairRabbit"
themesDir = "themes"
theme = "rr-1"
googleAnalytics = "UA-112062782-1"
[taxonomies]
  tag = "tags"
  category = "categories"
[params]
  tagLine = "Let’s enhance your repair business with our self hosted software"
