# Site settings
baseURL = "http://repairrabbit.gitlab.io/"
languageCode = "en-us"
title = "RepairRabbit"
themesDir = "themes"
theme = "rr-1"
googleAnalytics = "UA-112062782-1"
[taxonomies]
  tag = "tags"
  category = "categories"
[params]
  tagLine = "Let’s scale your repairing business with our ready to use system"
