# Site settings
baseURL = "http://repairrabbit.gitlab.io/"
languageCode = "en-us"
title = "Repair Rabbit"
themesDir = "themes"
theme = "rr-1"
[taxonomies]
  tag = "tags"
  category = "categories"
[params]
  tagLine = "Let’s scale your repairing business with our ready to use system"
# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-112062782-1"
