# Site settings
baseURL = "https://www.repairrabbit.co/"
languageCode = "en-us"
title = "RepairRabbit"
themesDir = "themes"
theme = "rr-1"
googleAnalytics = "G-2VM9Z9STTQ"
[taxonomies]
  tag = "tags"
  category = "categories"
[params]
  env = "development"
  tagLine = "Enhance your repair business with RepairRabbit"
